Implemented HashTable class
itmo-java-basics-2020/task-3-hashtable-classes-inner-classes-class-object-annihilator01 pull request #1
Opened 2020-03-13 22:21 UTC by annihilator01

- Implemented .resize() method for array expansion
- Added threshold variable for defining when using .resize()
- Added constructor with loadFactor
- Implemented all default methods

2020-03-23 12:31 UTC, AfanasievYuriy requested changes

2020-03-23 12:31 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +        Object key;
поля класса ВСЕГДА с наименьшим уровнем открытости

2020-03-23 12:31 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int size;
поля класса принято объявлять в самом верху тела класса

2020-03-23 12:31 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +        int putBucketIndex = (reusableBucketIndex == -1) ? hashIndex
возможно есть другие способы, но я настаиваю на варианте:
![image](https://user-images.githubusercontent.com/20247104/77316940-583a9400-6d1b-11ea-9db3-d9a8d170484f.png)

2020-03-23 13:35 UTC, annihilator01 commented on src/main/java/ru/itmo/java/HashTable.java
> +        Object key;
Я ориентировался на реализацию HashMap в Java. Все такие статические константные переменные почему-то без модификатора private. 
![class_vars](https://user-images.githubusercontent.com/43321035/77321685-96d44c80-6d23-11ea-816b-50b9b8ce7a2f.png)

2020-03-23 13:40 UTC, iamdubrovskii commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int size;
В этом случае так же ориентировался на реализацию HashMap.
Там структура такова: статические константные переменные -> статический внутренний класс -> поля основного класса -> методы
В связи с этим такой вопрос, насколько корректно смотреть на структуру кода в официальных библиотеках языка, по идее они же тоже должны соблюдать стайлинг?

2020-03-23 13:43 UTC, annihilator01 commented on src/main/java/ru/itmo/java/HashTable.java
> +        int putBucketIndex = (reusableBucketIndex == -1) ? hashIndex
Нашёл три варианта, выбрал второй.
Насколько критично будет продолжать использовать второй, он как-то больше по нраву?
![image](https://user-images.githubusercontent.com/43321035/77322766-48c04880-6d25-11ea-8386-1ea03f9a5974.png)

2020-03-23 13:44 UTC, iamdubrovskii commented on src/main/java/ru/itmo/java/HashTable.java
> +        int putBucketIndex = (reusableBucketIndex == -1) ? hashIndex
ну или конечно первый, если имена переменных достаточно короткие

2020-03-28 00:35 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +        Object key;
> Я ориентировался на реализацию HashMap в Java. Все такие статические константные переменные почему-то без модификатора private.
> ![class_vars](https://user-images.githubusercontent.com/43321035/77321685-96d44c80-6d23-11ea-816b-50b9b8ce7a2f.png)

внимательнее смотри на какую строку указывает комментарий в пулл реквесте - это строка 12 с полем класса Entry

2020-03-28 00:44 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int size;
слушай, вопрос неоднозначный, вот выдержка из стайлгайда (это порядок объявления):
```
Static variable field declarations
Instance variable field declarations
Static initializer
Static member inner class declarations [*]
Static method declarations
Instance initializer
Instance constructor declarations
Instance member inner class declarations [*]
Instance method declarations
```

Дело в том, что на практике статика (классы, инишиалайзеры и прочее) очень редко встречется, поэтому все (ну, из того что я видел) придерживаются порядка 
`статик поля -> инстанс поля -> конструкторы`
Многое зависит от договоренностей внутри команды, поэтому мы договоримся писать 
`статик поля -> инстанс поля -> конструкторы`

:)

2020-03-28 00:52 UTC, AfanasievYuriy commented on src/main/java/ru/itmo/java/HashTable.java
> +        int putBucketIndex = (reusableBucketIndex == -1) ? hashIndex
я не против (но с третьим места больше остается)

2020-03-28 00:53 UTC, AfanasievYuriy approved these changes

2020-03-28 13:22 UTC, annihilator01 commented on src/main/java/ru/itmo/java/HashTable.java
> +        Object key;
Понял, будет поправлено.

2020-03-28 13:23 UTC, annihilator01 commented on src/main/java/ru/itmo/java/HashTable.java
> +    private int size;
Хорошо, уловил, теперь буду по договоренности :)

2020-03-28 13:26 UTC, annihilator01 commented on src/main/java/ru/itmo/java/HashTable.java
> +        int putBucketIndex = (reusableBucketIndex == -1) ? hashIndex
да, третий для больших выражений лучше подходит

2020-03-28 13:34 UTC, merged